name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        items:
          - os: ubuntu-latest
            arch: x86_64-linux
    name: "Build ${{ matrix.items.arch }}"
    runs-on: ${{ matrix.items.os }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix run .# -- --headless -c "q" 2>&1 | grep "Error detected while" || exit 0
