name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        items:
          - os: ubuntu-latest
            arch: x86_64-linux
          - os: darwin-latest
            arch: aarch64-darwin
    name: "Build ${{ matrix.items.arch }}"
    runs-on: ${{ matrix.items.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build
