name: Job - Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN" # Every sunday at midnight

jobs:
  build:
    strategy:
      matrix:
        items:
          - os: ubuntu-latest
            arch: x86_64-linux
    name: "Build ${{ matrix.items.arch }}"
    runs-on: ${{ matrix.items.os }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix flake update
      - run: nix run .# -- --headless -c "q" 2>&1 | grep "Error detected while" || exit 0
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update flake"
